[package]
name = "hoek"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "hoek.io root crate"
homepage = "https://hoek.io"
repository = "https://github.com/khoek/rust-hoek"

[dependencies]
